"""Prospective policy rosters and finite-catalog dependence sensitivity.

No simulator worlds or final outcomes are generated by this module.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

from .artifacts import digest
from .inference import paired_cluster_estimate
from .simulator import FAMILIES, rng


PILOT_INPUT_BINDINGS = {
    "environment_lock_sha256": "reports/environment/ENVIRONMENT_LOCK.json",
    "warmstart_pointer_sha256": "reports/policy/WARMSTART_LATEST.json",
    "support_pointer_sha256": "reports/policy/SUPPORT_V2_QUALIFICATION.json",
    "incident_detector_pointer_sha256": "reports/incidents/DETECTOR_FREEZE.json",
}


def verify_pilot_inputs(root: Path, protocol: dict) -> None:
    for key, relative in PILOT_INPUT_BINDINGS.items():
        if digest(root / relative) != protocol[key]:
            raise ValueError("Pilot environment/model/support changed: " + relative)


def verified_episode_record(path: Path, world: dict, arm: str, protocol_sha256: str, *, stage: str) -> dict:
    if stage not in {"pilot", "final"} or world["stage"] != stage:
        raise ValueError("Explicit matching pilot/final episode stage required")
    receipt = path.with_suffix(".receipt.json")
    if path.is_symlink() or receipt.is_symlink() or not receipt.exists() or json.loads(receipt.read_text())["sha256"] != digest(path):
        raise ValueError("Interrupted world lacks verified durable receipt")
    record = json.loads(path.read_text())
    if record["world"] != world or record["arm"] != arm or record["protocol_sha256"] != protocol_sha256 or record["excluded_from_confirmation"] != (stage == "pilot"):
        raise ValueError("World identity changed")
    evaluation = record["evaluation"]
    if evaluation["world_id"] != world["world_id"] or evaluation["family"] != world["family"] or evaluation["stage"] != stage or evaluation["final_pending_exposures"] != 0 or evaluation["snapshot_reward_updates_before_day7"] != 0 or not math.isfinite(evaluation["utility"]):
        raise ValueError("Incomplete or invalid episode")
    return record


def verified_pilot_record(path: Path, world: dict, arm: str, protocol_sha256: str) -> dict:
    return verified_episode_record(path, world, arm, protocol_sha256, stage="pilot")


def world_roster(stage: str, count: int) -> list[dict]:
    if type(count) is not int:
        raise ValueError("Integer world count required")
    if stage == "pilot":
        if count != 20:
            raise ValueError("Exactly twenty excluded pilot worlds required")
        first = 64
    elif stage == "final":
        if not 40 <= count <= 200 or count % 4:
            raise ValueError("Frozen final count must be40–200, balanced across four families")
        first = 48
    else:
        raise ValueError("Only excluded pilot or frozen final roster permitted")
    return [{"world_id": f"policy-{stage}-world{number}",
             "family": FAMILIES[number % 4], "stage": stage,
             "parameter_index": first + number % 16,
             "budget_per_campaign": int(rng(f"policy-{stage}-world{number}", 0, -1,
                                            "initial_budget_uniform_prior").choice((4000, 10000, 20000)))}
            for number in range(count)]


def paired_analysis(worlds: list[dict], candidate: np.ndarray, baseline: np.ndarray,
                    *, bootstrap_draws: int = 10000) -> dict:
    candidate, baseline = np.asarray(candidate, dtype=float), np.asarray(baseline, dtype=float)
    if candidate.shape != (len(worlds),) or baseline.shape != candidate.shape:
        raise ValueError("One completed paired utility per declared world required")
    ids = [item["world_id"] for item in worlds]
    families = [item["family"] for item in worlds]
    primary = paired_cluster_estimate(ids, candidate[:, None], baseline[:, None],
        strata=families, bootstrap_draws=bootstrap_draws)
    blocks = sorted({(item["family"], item["parameter_index"]) for item in worlds})
    block_candidate, block_baseline, block_families = [], [], []
    for family, index in blocks:
        mask = np.array([(item["family"], item["parameter_index"]) == (family, index) for item in worlds])
        block_candidate.append(candidate[mask].mean())
        block_baseline.append(baseline[mask].mean())
        block_families.append(family)
    sensitivity = paired_cluster_estimate([f"{family}:{index}" for family, index in blocks],
        np.array(block_candidate)[:, None], np.array(block_baseline)[:, None],
        strata=block_families, bootstrap_draws=bootstrap_draws)
    def record(estimate):
        return {"mean": estimate.mean, "lower": estimate.lower, "upper": estimate.upper,
                "units": estimate.independent_units, "per_unit": list(estimate.per_unit)}
    return {"primary_paired_complete_world": record(primary),
            "parameter_block_cluster_sensitivity": record(sensitivity),
            "assumptions": ["Independent exogenous worlds conditional on the frozen finite parameter catalog",
                            "Repeated shocks do not create new mechanism families or parameter blocks",
                            "Block sensitivity equally weights catalog blocks, not repeated world counts",
                            "Equal family weighting; no production generalization claim"]}
